<a href="https://colab.research.google.com/github/QMBC-Python/QMBC-Python.github.io/blob/main/content/IntrotoArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.4 - Intro to Arrays

In [ ]:
#@markdown Video: Intro to Arrays
from IPython.display import YouTubeVideo
video = YouTubeVideo(id="-nqZEtNz6oY", width=854, height=480, fs=1)
print("Video available at https://youtube.com/watch?v=" + video.id)
video

**What is Numpy?**

NumPy = Numerical Python

Core library for scientific computing

Most "Matlab-y" data type

Lots of documentation: https://numpy.org/doc/stable/reference/

Lots of tutorials including: https://cs231n.github.io/python-numpy-tutorial/



In [ ]:
import numpy as np

## Array overview

Arrays are a new data type!

In [ ]:
x = np.array([5, 1, 2])

x

array([5, 1, 2])

![picture](https://raw.githubusercontent.com/QMBC-Python/QMBC-Python.github.io/main/images/numpy_1d.png)

In [ ]:
x = np.array([[3, 2], [1, 4]])

print(x)

[[3 2]
 [1 4]]


![picture](https://raw.githubusercontent.com/QMBC-Python/QMBC-Python.github.io/main/images/numpy_1d2d3d.png)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([[3.1, 2], [1.2, 4]])

x.dtype

dtype('float64')

You can manually set the data type during array creation.

In [ ]:
x = np.array([[3.1, 2], [1.2, 4]], dtype = 'int')

print(x)

[[3 2]
 [1 4]]


You can also change the data type later

In [ ]:
x = x.astype('float')

x.dtype

dtype('float64')

In [ ]:
x.shape

(2, 2)

## Creating arrays

There are many ways to intialize arrays. Let's start with the basics

1) Initialize with numbers in closed brackets (python lists)

In [ ]:
x = np.array([4, 6, 1])

x

array([4, 6, 1])

In [ ]:
x = np.array([[4, 6, 1], [3, 4, 5]])

print(x)
print(x.shape)

[[4 6 1]
 [3 4 5]]
(2, 3)


2) Initialize with zeros or ones

In [ ]:
x = np.zeros(shape = (2, 2, 4, 8, 10, 2))

x.shape

(2, 2, 4, 8, 10, 2)

In [ ]:
x = np.ones(shape = (5, 1))

4) Initialize with evenly space numbers

Given interval and step size:

In [ ]:
x = np.arange(start = 0, stop = 10, step = 2)

print(x)

[0 2 4 6 8]


In [ ]:
x = np.arange(0, 10, 2)

print(x)

[0 2 4 6 8]


Given interval and specified number of points:

In [ ]:
x = np.linspace(start = 0, stop = 10, num = 50)

print(x)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


6) Initialize with randomly drawn numbers

We will return to this one later

7) Initialize with loaded data

We will return to this one later

## Basic computations

We will cover basics and examples here but there are hundreds of Numpy possibilities - you will have to Google!

https://numpy.org/doc/stable/reference/index.html

In [ ]:
x = np.array([[3, 4], [1, 2]])

print(x)

[[3 4]
 [1 2]]


In [ ]:
x + 1

array([[4, 5],
       [2, 3]])

In [ ]:
y = np.array([[0, 1], [0, 3]])

x + y

array([[3, 5],
       [1, 5]])

In [ ]:
x * y

array([[0, 4],
       [0, 6]])

In [ ]:
x @ y

array([[ 0, 15],
       [ 0,  7]])

In [ ]:
print(x)

[[3 4]
 [1 2]]


In [ ]:
np.sum(x)

10

In [ ]:
np.sum(x, axis = 0)

array([4, 6])

![picture](https://raw.githubusercontent.com/QMBC-Python/QMBC-Python.github.io/main/images/numpy_axes.png)

In [ ]:
np.mean(x, axis = 1)

array([3.5, 1.5])

## Concatenating & reshaping arrays

In [ ]:
y = np.concatenate((x, x), axis = 1)

y

array([[3, 4, 3, 4],
       [1, 2, 1, 2]])

In [ ]:
y = np.concatenate((x, x), axis = 0)

y

array([[3, 4],
       [1, 2],
       [3, 4],
       [1, 2]])

In [ ]:
np.hstack((x, x))
np.vstack((x, x))


array([[3, 4],
       [1, 2],
       [3, 4],
       [1, 2]])

Reshaping arrays

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
y = np.reshape(x, newshape = (6, 1))

print(y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
y = x.reshape((6, 1))

print(y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
y = x.reshape((-1, 1))

print(y)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
y = x.reshape((3, 2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
y = x.reshape((4, 2))

ValueError: ignored

![picture](https://raw.githubusercontent.com/QMBC-Python/QMBC-Python.github.io/main/images/numpy_reshape.png)