<a href="https://colab.research.google.com/github/ebatty/ComputationalBootcamp/blob/master/content/ArrayComputations.ipynb" target="_blank"><img alt="Open In Colab" src="https://colab.research.google.com/assets/colab-badge.svg"/></a>

# Array Computations

 Video


In [ ]:
#@markdown Video
from IPython.display import YouTubeVideo
video = YouTubeVideo(id="h_KYkTFkfNw", width=730, height=410, fs=1)
print("Video available at https://youtube.com/watch?v=" + video.id)
video

# Setting up our data

Let's say we have spiking data in an array. Each column is a neuron, each row is a time point. The data represents spike counts.

![picture](https://raw.githubusercontent.com/ebatty/ComputationalBootcamp/master/images/data.png)

We can create the above array as follows:

In [ ]:
import numpy as np
spikes = np.array([[1, 0, 1], [3, 4, 1]])

# Investigating the data

We can compute the shape of the array (to get the number of rows and columns)

In [ ]:
np.shape(spikes)

(2, 3)

The first number outputted above is the number of rows, the second is the number of columns.

We can also get the minimum and maximum values in the array

In [ ]:
np.min(spikes)

0

In [ ]:
np.max(spikes)

4

We can sum over all the values in the array, or get the mean of all values as follows:

In [ ]:
np.sum(spikes)

10

In [ ]:
np.mean(spikes)

1.6666666666666667

# Axis-specific computations

We might want to get the mean per column or per row, instead of over the whole array. We can do this with the following code:

`np.mean(spikes, axis = ?)`

Where the question mark is needs to be replaced with the axis that we want to compute over. 

The rows are axis 0, when we enter axis = 0 as an argument into the np.mean command, we are asking numpy to compute the mean over the rows (which would be the column means)

![picture](https://raw.githubusercontent.com/ebatty/ComputationalBootcamp/master/images/axes.png)

We can get the mean over rows with:

In [ ]:
np.mean(spikes, axis = 1)

array([0.66666667, 2.66666667])

We can get the mean over columns with:

In [ ]:
np.mean(spikes, axis = 0)

array([2., 2., 1.])

# Vectorization

If you do something like a math operation on an array, it will do element-wise operation

![picture](https://raw.githubusercontent.com/ebatty/ComputationalBootcamp/master/images/addition.png)

In [ ]:
spikes + 1

array([[2, 1, 2],
       [4, 5, 2]])

If we do something like added two arrays of the same shape, that will also be element-wise.

![picture](https://raw.githubusercontent.com/ebatty/ComputationalBootcamp/master/images/addition_two_arrays.png)

In [ ]:
y = np.array([[2, 3, 0], [4, 1, 1]])

spikes + y

array([[3, 3, 1],
       [7, 5, 2]])