<a href="https://colab.research.google.com/github/ebatty/ComputationalBootcamp/blob/master/content/CreatingReshaping.ipynb" target="_blank"><img alt="Open In Colab" src="https://colab.research.google.com/assets/colab-badge.svg"/></a>

# Creating & Reshaping Arrays

In [3]:
import numpy as np

## Creating Arrays

There are many ways to intialize arrays. Let's start with the basics

1) Initialize with numbers in closed brackets (python lists)

In [ ]:
x = np.array([4, 6, 1])

x

array([4, 6, 1])

In [ ]:
x = np.array([[4, 6, 1], [3, 4, 5]])

print(x)
print(x.shape)

[[4 6 1]
 [3 4 5]]
(2, 3)


2) Initialize with zeros or ones

In [ ]:
x = np.zeros(shape = (2, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x = np.ones(shape = (5, 1))
x

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

3. Initialize with evenly spaced numbers

Given interval and step size:

In [ ]:
x = np.arange(start = 0, stop = 10, step = 2)

print(x)

[0 2 4 6 8]


Given interval and specified number of points:

In [ ]:
x = np.linspace(start = 0, stop = 10, num = 50)

print(x)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


6) Initialize with randomly drawn numbers

We will return to this one later

7) Initialize with loaded data

We will return to this one later

## Concatenating arrays

In [4]:
x = np.array([[3, 2], [1, 4]])

print(x)

[[3 2]
 [1 4]]


In [5]:
y = np.concatenate((x, x), axis = 1)

y

array([[3, 2, 3, 2],
       [1, 4, 1, 4]])

In [6]:
y = np.concatenate((x, x), axis = 0)

y

array([[3, 2],
       [1, 4],
       [3, 2],
       [1, 4]])

## Reshaping arrays

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
y = np.reshape(x, newshape = (6, 1))

print(y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
y = x.reshape((6, 1))

print(y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
y = x.reshape((3, 2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
x = np.zeros((5, 7, 10))

y = x.reshape((5, -1))

y.shape

(5, 70)