<a href="https://colab.research.google.com/github/ebatty/ComputationalBootcamp/blob/master/content/Indexing.ipynb" target="_blank"><img alt="Open In Colab" src="https://colab.research.google.com/assets/colab-badge.svg"/></a>

# Indexing

In [2]:
import numpy as np

Let's first create this array

![picture](https://raw.githubusercontent.com/ebatty/ComputationalBootcamp/master/images/array.png)

In [3]:
x = np.array([[4, 2, 1, 3], [1, 0, 3, 5], [6, 7, 8, 2]])

We can grab specific data points using:

`x[row index, column index]`

In [ ]:
x[2, 1]

7

We can grab multiple column values in one row with:
```
x[row index, start index:stop index*]
```

\* not inclusive of stop index

In [ ]:
x[0, 1:3]

array([2, 1])

We can overwrite subsets of our array.

In [ ]:
x[0, 0] = 100

In [ ]:
x

array([[100,   2,   1,   3],
       [  1,   0,   3,   5],
       [  6,   7,   8,   2]])

In [ ]:
x[0, :] = 100

In [ ]:
x

array([[100, 100, 100, 100],
       [  1,   0,   3,   5],
       [  6,   7,   8,   2]])

We can use Boolean indexing as well!

In [4]:
x > 6

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True, False]])

In [5]:
x[x > 6]

array([7, 8])

In [6]:
boolean_columns = np.array([False, False, True, True])

x[:, boolean_columns]

array([[1, 3],
       [3, 5],
       [8, 2]])